//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VendeTodo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetalleCompra
    {
        public int DetalleCompraID { get; set; }
        public int CompraID { get; set; }
        public decimal MontoParcial { get; set; }
        public bool EsEfectivo { get; set; }
    
        public virtual Compra Compra { get; set; }
    }
}
