//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VendeTodo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetalleCuenta
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DetalleCuenta()
        {
            this.Compra = new HashSet<Compra>();
            this.HistorialCuenta = new HashSet<HistorialCuenta>();
            this.Pago = new HashSet<Pago>();
        }
    
        public int DetallaCuentaID { get; set; }
        public int CuentaID { get; set; }
        public Nullable<int> TasaInteresCompensatoriaID { get; set; }
        public int TasaInteresMoratoriaID { get; set; }
        public System.DateTime FechaInicio { get; set; }
        public System.DateTime FechaFinal { get; set; }
        public Nullable<decimal> PagoInicial { get; set; }
        public int EstadoID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Compra> Compra { get; set; }
        public virtual Cuenta Cuenta { get; set; }
        public virtual EstadoDetalleCuenta EstadoDetalleCuenta { get; set; }
        public virtual TasaInteres TasaInteres { get; set; }
        public virtual TasaInteres TasaInteres1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HistorialCuenta> HistorialCuenta { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pago> Pago { get; set; }
    }
}
