//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VendeTodo.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FinanzasEntities : DbContext
    {
        public FinanzasEntities()
            : base("name=FinanzasEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Compra> Compra { get; set; }
        public virtual DbSet<Cuenta> Cuenta { get; set; }
        public virtual DbSet<DetalleCompra> DetalleCompra { get; set; }
        public virtual DbSet<DetalleCuenta> DetalleCuenta { get; set; }
        public virtual DbSet<EstadoDetalleCuenta> EstadoDetalleCuenta { get; set; }
        public virtual DbSet<HistorialCuenta> HistorialCuenta { get; set; }
        public virtual DbSet<Pago> Pago { get; set; }
        public virtual DbSet<Producto> Producto { get; set; }
        public virtual DbSet<ProductoCompra> ProductoCompra { get; set; }
        public virtual DbSet<TasaInteres> TasaInteres { get; set; }
        public virtual DbSet<TipoInteres> TipoInteres { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
    }
}
