//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VendeTodo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pago
    {
        public int PagoID { get; set; }
        public int DetalleCuentaID { get; set; }
        public System.DateTime FechaPago { get; set; }
        public decimal MontoPago { get; set; }
    
        public virtual DetalleCuenta DetalleCuenta { get; set; }
    }
}
