//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VendeTodo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TasaInteres
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TasaInteres()
        {
            this.DetalleCuenta = new HashSet<DetalleCuenta>();
        }
    
        public int TasaInteresID { get; set; }
        public decimal Interes { get; set; }
        public int TipoInteresID { get; set; }
        public int TiempoInteres { get; set; }
        public Nullable<int> PeriodoCapitalizacion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleCuenta> DetalleCuenta { get; set; }
        public virtual TipoInteres TipoInteres { get; set; }
    }
}
